---
- name: install fail2ban and sendmail
  package:
    name:
      - fail2ban
      - sendmail
      - whois
    state: present

- name: get IP of controller
  uri:
    url: http://ifconfig.me/ip
    return_content: true
  register: ip_response
  connection: local
  delegate_to: localhost
  become: false  # do not attempt to become, because maybe passwords

- name: copy fail2ban config
  template:
    src: fail2ban.jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: 0644

- name: hostname fixup FQDN for sendmail
  hostname:
    name: "{{ inventory_hostname }}"

- name: start/enable fail2ban/sendmail
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop:
    - sendmail
    - fail2ban
