---
- name: add telegraf yum repo
  yum_repository:
    name: influxdb
    description: InfluxDB Repository - RHEL $releasever
    baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
    gpgcheck: true
    gpgkey: https://repos.influxdata.com/influxdb.key
  when: (ansible_distribution == 'CentOS') and (lookup('env', 'container') != 'docker')

- name: install telegraf
  package:
    name: telegraf
    state: present

- name: copy telegraf config
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    mode: 0644

- name: start/enable telegraf service
  systemd:
    name: telegraf
    state: restarted
    enabled: true
