---
- name: add nginx-mainline repo
  yum_repository:
    name: nginx-mainline
    description: nginx mainline repo
    baseurl: http://nginx.org/packages/mainline/centos/$releasever/$basearch/
    gpgcheck: true
    enabled: true
    gpgkey: https://nginx.org/keys/nginx_signing.key

- name: install nginx
  package:
    name: nginx
    state: latest # noqa 403 usually always stable

- name: set nginx.conf in /etc/nginx/
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644

- name: enable nginx
  systemd:
    name: nginx
    state: started
    enabled: true
