---
- name: Master Playbook
  hosts: inthemainfra.me
  become: true
  roles:
    # yamllint disable rule:comments-indentation
    # - baseline
    # - bitwarden
    # - caddy
    # - docker
    # - duo
    - factorio
    # - firewalld
    # - k3s
    # - letsencrypt
    # - plex
    # - proxmox
    # - step_ca
    # - swap
    # - vault
    # yamllint enable rule:comments-indentation
  handlers:
    - import_tasks: roles/caddy/handlers/main.yml
    - import_tasks: roles/firewalld/handlers/main.yml
