---
- name: remove login nag
  replace:
    path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
    regexp: "data.status !== 'Active'"
    replace: "false"

- name: restart pveproxy
  service:
    name: pveproxy
    state: restarted

- name: remove enterprise upstream
  file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: add pve-no-subscription
  lineinfile:
    path: /etc/apt/sources.list.d/pve-no-subscription.list
    line: deb http://download.proxmox.com/debian/pve buster pve-no-subscription
    state: present
    create: true
    mode: 0755

- name: pull turnkey updates # noqa 301
  command: pveam update
