---
- name: install docker/podman
  package:
    name: "{{ container_package }}"
    state: latest # noqa package-latest

- name: install Docker SDK for Python
  pip:
    name: docker
    state: latest # noqa package-latest
  when:
    - container_package == 'docker'
    - lookup('env', 'container') != 'docker'

- name: enable/start docker service
  service:
    name: docker
    state: started
    enabled: true
  when:
    - container_package == 'docker'
    - lookup('env', 'container') != 'docker'
